const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const locations=[{name:'Seattle',setting:'Capitol Hill · Food truck',address:'1000 E Madison St, Seattle, WA 98122',hours:'Hours to be confirmed',url:'https://www.doordash.com/en/business/momo-king-11421229/',label:'Find Seattle on DoorDash'},{name:'Tacoma',setting:'Tacoma Mall · Food court',address:'4502 S Steele St, Tacoma, WA 98409',hours:'Listed hours: Mon–Sat 10–8 · Sun 11–6',url:'https://www.doordash.com/store/momo-king-24583139/',label:'Order Tacoma'},{name:'Olympia',setting:'Capital Mall · Food court',address:'625 Black Lake Blvd SW, Olympia, WA 98502',hours:'Hours to be confirmed',url:'https://order.online/store/the-momo-king-35718867',label:'Order Olympia'}];
const fillingIngredients = {
Chicken: 'All-purpose flour wrap with a filling of ground chicken, onion, garlic, ginger, cilantro, butter, and a slew of Nepali spices.',
Pork: 'All-purpose flour wrap with a filling of ground pork, onion, garlic, ginger, cilantro, butter, and a slew of Nepali spices.',
Vegetarian: 'All-purpose flour wrap with a filling of mixed vegetables, Nepalese cheese, garlic, ginger, cilantro, butter, and a slew of Nepali spices.'
};
const steps=[{name:'Filling',title:'What’s on the inside?',guide:'Let’s start with the good stuff inside.',options:[['Chicken','Savory, comforting, and full of flavor.'],['Pork','Rich, juicy, and made for a bold sauce.'],['Vegetarian','A little garden in every bite.']]},{name:'Style',title:'How do you like your folds?',guide:'Soft and steamy, or a little crispy? Your call.',options:[['Steamed','Soft, delicate wrappers. A momo classic.'],['Fried','Golden on the outside, happiness inside.']]},{name:'Sauce',title:'Now, make it your own.',guide:'The finishing touch. Let’s get a little saucy.',options:[['Classic dip','Sweet sesame sauce and hot chili sauce on the side.'],['Butter','A rich, comforting butter curry sauce.'],['Chili','Sweet heat for a lively little kick.'],['Coconut','Creamy coconut curry.'],['Jhol','A savory sesame and peanut soup.'],['Cheese','A creamy, cheesy curry sauce.']]}];let step=0;const selected=['Chicken','Steamed','Classic dip'];let built=false;
function renderBuilder(){ $('.steps').innerHTML=steps.map((s,i)=>`<button class="${i===step?'active':''}" ${i===step?'aria-current="step"':''} data-step="${i}"><b>${i+1}</b>${s.name}</button>`).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;renderBuilder()});$('#step-title').textContent=steps[step].title;$('#guide-text').textContent=steps[step].guide;$('#choices').innerHTML=steps[step].options.map(([name,desc])=>`<button class="choice ${selected[step]===name?'selected':''}" aria-pressed="${selected[step]===name}" data-choice="${name}"><span class="radio" aria-hidden="true"></span><span><strong>${name}</strong><small>${desc}</small></span></button>`).join('');$$('[data-choice]').forEach(b=>b.onclick=()=>{selected[step]=b.dataset.choice;built=true;renderBuilder()});$('#back').disabled=step===0;$('#next').textContent=step===2?'Find my momo ↗':`Next: ${step===0?'cooking style':'sauce'} →`;$('#combo-name').textContent=`${selected[2]==='Classic dip'?'':selected[2]+' '}${selected[0]==='Vegetarian'?'Vegetable':selected[0]} momo`;$('#combo-desc').textContent=`${selected[1]} momo with ${selected[2]==='Classic dip'?'sweet sesame sauce and hot chili sauce on the side':selected[2].toLowerCase()+' sauce'}.`;$('#combo-tags').innerHTML=selected[0]==='Vegetarian'?'<div class="tags">Vegetarian</div>':'';$('#combo-ingredients').textContent=fillingIngredients[selected[0]];}
$('#back').onclick=()=>{if(step>0){step--;renderBuilder()}};$('#next').onclick=()=>{built=true;if(step<2){step++;renderBuilder();$('#step-title').setAttribute('tabindex','-1');$('#step-title').focus({preventScroll:true})}else openOrder(`${selected[1]} ${selected[0].toLowerCase()} momo · ${selected[2]}`)};renderBuilder();
function openOrder(summary){$('#order-summary').textContent=summary?`Your pick: ${summary}. Choose where to order.`:'Choose your Momo King location.';$('#location-dialog').showModal()}
$$('.order-link').forEach(b=>b.onclick=()=>openOrder());
$('#locations-grid').innerHTML=locations.map((l,i)=>`<article class="location"><span class="number">0${i+1} / WASHINGTON</span><h3>${l.name}</h3><p>${l.setting}<br>${l.address}</p><p class="hours">${l.hours}</p><div class="location-actions"><button data-location="${i}">Order here ↗</button><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('Momo King '+l.address)}" target="_blank" rel="noopener">Get directions</a></div></article>`).join('');
$$('[data-location]').forEach(b=>b.onclick=()=>{openOrder();const index=+b.dataset.location;$('#order-summary').textContent=`${locations[index].name} selected. Continue to its ordering service below.`;$('#order-locations').querySelectorAll('a')[index].focus()});
$('#order-locations').innerHTML=locations.map(l=>`<a class="order-destination" href="${l.url}" target="_blank" rel="noopener"><span>${l.name}<small>${l.label}</small></span><span aria-hidden="true">↗</span></a>`).join('');
const dishes=[{name:'Classic momo',category:'Momos',desc:'Simple folds, big flavor. Choose chicken, pork, or vegetarian filling.',ingredients:'Served with sweet sesame sauce and hot chili sauce on the side.',art:'photo'},{name:'Butter momo',category:'Momos',desc:'Your favorite dumplings tucked into a rich butter curry sauce.',ingredients:'Momos and butter curry sauce. Contains dairy; complete allergens to confirm.',art:'sauce'},{name:'Chili momo',category:'Momos',desc:'A sweet and spicy sauce for a bolder bite.',ingredients:'Momos and sweet chili sauce. Full recipe and allergens to confirm.',art:'sauce'},{name:'Jhol momo',category:'Momos',desc:'Comfort by the spoonful, in a savory sesame and peanut soup.',ingredients:'Momos, sesame and peanut soup. Contains sesame and peanuts; complete allergens to confirm.',art:'sauce'},{name:'Nepalese chowmein',category:'More favorites',desc:'Stir-fried noodles, vegetables, and Nepalese-style seasoning.',ingredients:'Noodles, mixed vegetables, seasonings and optional meat. Full recipe and allergens to confirm.',art:'chowmein'},{name:'Fried rice',category:'More favorites',desc:'A hearty plate of rice with vegetables and your choice of filling.',ingredients:'Rice, vegetables, seasoning and optional meat. Full recipe and allergens to confirm.',art:'chowmein'},{name:'Frankie rolls',category:'More favorites',desc:'A satisfying wrap filled with vegetables and Nepalese-inspired flavors.',ingredients:'Tortilla, filling and sauce. Full recipe and allergens to confirm.',art:'chowmein'},{name:'Mango lassi',category:'Drinks',desc:'Cool, creamy, and a sweet companion to a little heat.',ingredients:'Mango and yogurt. Contains dairy; complete recipe to confirm.',art:'drinks'}];
dishes.push(
{name:'Cheese momo',category:'Momos',desc:'Momos in a creamy, cheesy curry sauce.',ingredients:'Your choice of momo filling with cheese curry sauce. Full sauce ingredients to confirm.',art:'sauce'},
{name:'Coco momo',category:'Momos',desc:'Soft folds meet a creamy coconut curry sauce.',ingredients:'Your choice of momo filling with coconut curry sauce. Full sauce ingredients to confirm.',art:'sauce'},
{name:'Banana lassi',category:'Drinks',desc:'A creamy banana yogurt drink.',ingredients:'Banana and yogurt. Full recipe to confirm.',art:'drinks'},
{name:'Sweet lassi',category:'Drinks',desc:'A sweet, refreshing yogurt drink.',ingredients:'Sweetened yogurt drink. Full recipe to confirm.',art:'drinks'},
{name:'Salty lassi',category:'Drinks',desc:'A refreshing, savory yogurt drink.',ingredients:'Salted yogurt drink. Full recipe to confirm.',art:'drinks'},
{name:'Basmati rice',category:'Sides',desc:'A simple side of basmati rice to enjoy with your meal.',ingredients:'Basmati rice. Preparation details to confirm.',art:'rice'},
{name:'Fries',category:'Sides',desc:'A side of golden fries for a little extra crunch.',ingredients:'Potatoes. Oil and seasoning details to confirm.',art:'fries'}
);
const categoryOrder=['Momos','More favorites','Sides','Drinks'];
dishes.sort((a,b)=>categoryOrder.indexOf(a.category)-categoryOrder.indexOf(b.category));

function art(d){if(d.art==='rice')return '<svg viewBox="0 0 120 120" aria-hidden="true"><ellipse cx="60" cy="55" rx="43" ry="24" fill="#fff9e4"/><path d="M14 55h92c-5 33-25 44-46 44S19 88 14 55Z" fill="#b9442c"/><path d="m34 45 7-3m6 6 8-3m3-10 7 2m7 12 8-3m-39-9 6-2m38 6 7 3" stroke="#d6c6a2" stroke-width="3" stroke-linecap="round"/></svg>';if(d.art==='fries')return '<svg viewBox="0 0 120 120" aria-hidden="true"><g fill="#e9b650" stroke="#c99131" stroke-width="2"><path d="m30 69-5-42 12-2 6 46ZM44 66V17h12v49ZM60 70l4-47 12 1-4 46ZM75 70l9-35 12 3-10 37Z"/></g><path d="m25 57 12 48h47l13-48q-36 21-72 0Z" fill="#b63825"/></svg>';if(d.art==='photo')return '<img src="assets/momos.png" alt="Illustrative momo photograph" loading="lazy">';if(d.art==='drinks')return '<svg viewBox="0 0 120 120" aria-hidden="true"><path d="M36 27h51l-8 78H44Z" fill="#eeb34d" stroke="#6c562e" stroke-width="2"/><path d="m67 60 9-49h20" fill="none" stroke="#a83427" stroke-width="5"/><ellipse cx="61" cy="29" rx="25" ry="7" fill="#fff0bd"/><path d="M48 44v37" stroke="#ffe2a0" stroke-width="6" stroke-linecap="round"/></svg>';if(d.art==='chowmein')return '<svg viewBox="0 0 120 120" aria-hidden="true"><path d="M13 57h94c-4 36-26 47-47 47S19 90 13 57Z" fill="#b9442c"/><ellipse cx="60" cy="57" rx="47" ry="18" fill="#f4cd72"/><path d="M23 55q20-20 40 2t33-4M28 65q14-24 29-5t31 0M35 45q18 18 40 0" fill="none" stroke="#ac6f30" stroke-width="3"/><path d="m57 48 41-32m-31 37 40-29" stroke="#314d36" stroke-width="4"/></svg>';return '<svg viewBox="0 0 180 180" aria-hidden="true"><ellipse cx="90" cy="136" rx="83" ry="31" fill="#b9462e"/><use href="#momo" x="20" y="-2" width="140" height="140"/></svg>'}
function renderMenu(cat='All dishes'){$('.categories').innerHTML=['All dishes','Momos','More favorites','Sides','Drinks'].map(c=>`<button data-category="${c}" class="${c===cat?'active':''}" aria-pressed="${c===cat}">${c}</button>`).join('');$$('[data-category]').forEach(b=>b.onclick=()=>renderMenu(b.dataset.category));$('#menu-grid').innerHTML=dishes.map((d,i)=>cat==='All dishes'||cat===d.category?`<button class="menu-card" data-dish="${i}" aria-label="View ${d.name} details"><div class="dish-art ${d.art}">${art(d)}</div><h3>${d.name}</h3><p>${d.desc}</p><span class="detail-link">Explore dish ↗</span></button>`:'').join('');$$('[data-dish]').forEach(b=>b.onclick=()=>{const d=dishes[+b.dataset.dish];$('#dish-detail').innerHTML=`<div class="dish-art ${d.art}">${art(d)}</div><h2>${d.name}</h2><p>${d.desc}</p><h3>What’s inside</h3><p>${d.ingredients}</p>${d.category==='Momos'?Object.entries(fillingIngredients).map(([name,ingredients])=>`<h3>${name==='Vegetarian'?'Vegetable':name} filling</h3><p>${ingredients}</p>`).join(''):''}<p class="fineprint">Illustrative menu details. Check the selected location’s ordering menu for current prices and availability.</p>`;$('.dish-order').onclick=()=>{$('#dish-dialog').close();openOrder(d.name)};$('#dish-dialog').showModal()})}renderMenu();
$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function replay(){const old=$('.intro');const fresh=old.cloneNode(true);old.replaceWith(fresh)}$$('.home-link').forEach(a=>a.addEventListener('click',replay));window.addEventListener('pageshow',e=>{if(e.persisted)replay()});
